###############################################################################
# Copyright (c) 2025 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-2.0/
# 
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
#
#ISMESSAGEFILE FALSE
#NLS_ENCODING=UNICODE
#NLS_MESSAGEFORMAT_NONE
#

server.name=Server
server.desc=Configuration for the Liberty server.

server.description.name=Description
server.description.desc=Description of the server.

server.quiesce.timeout.name=Quiesce Timeout
server.quiesce.timeout.desc=The maximum time to wait for the server to quiesce during shutdown. Specify a positive integer followed by a unit of time: hours (h), minutes (m), or seconds (s). If a unit is omitted after a positive integer, seconds are assumed. Values can be combined (for example, 1m30s is equivalent to 90s and also 90). The default value is 30s.
